dist: xenial
language: python
python:
  - 3.6
  - 3.7
notifications:
  email:
    - nick.hand@phila.gov
env:
  global:
    - secure: ftqPKCSqI7WJC4voaq5XovkkvnSDVnKJFN/Y3lKR3EavNmlGeVRpMIbZkIBW881z7BRLu2dj3mrNhVn46z7texAFD1Zgpc0OOQ363dyCjesl+ILI4DUoQ6IfDGewoh9+AhSOHzkx/8rnrjImRyGbGjpHbrKJxxCjKVnQiOTUr/KWmNCx9Qee0OibwqG93xVd2R6REwoZAut43hitWR+I/Cwt+1GE7JDN3Q6JaZMhydAr2oBmmvhAD4zWMnnichk6j7lXsqeYbiG1Zj6kTcpGyz0jHwnR41IfUbC6wKJ8YE1GUG6WV/b/vtlm2fmUuYQ2Ns3xVy9AZYADSqOlD+tgsAGt7/Lq3gwKzXnoFcjhHJwgpVPWlUUq8Bu+vPSWwz3ceGmLvKA1hWTLlahV2k4IvbAsR2VVHJV6q7OgzqEkT9x8IBsSdHem5zRieACeeGZtHoz8c21VHRAZnTAAef/wBAF7XRCrRXq2olODOyv2byj0D73PUFji2hq8/FIocMekNbGSeWMC4GyLq4wmjou6pRPteDq53hhRD1pQjGPE4Une52WGMS2sH+nPJHby+568k56p9ycKNuoyyr/vwZqojQf/11bonDqbCLKIDA0GyNg5EqubheM1be9oIsss8vgIGnwmGN3W8ecvHBwqdG33OPhOQK/7KPfX70CVl1NywqU=
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.conda"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - "./miniconda.sh -b -p $HOME/miniconda"
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set auto_update_conda False
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION conda-build "conda=4.7.10" jinja2 anaconda-client
  - conda install -c conda-forge --yes --file requirements.txt
  - pip install .[dev]
script:
  - py.test . --cov osm2gpd
after_success:
  - coveralls
  - chmod +x deploy_anaconda.sh
deploy:
  - provider: pypi
    distributions: sdist
    user: controllerphl
    password:
      secure: JpPXibyQVdWiw2lALLu8CuhFquyfZsVFNzFAjXz/w8jbdw4i67KXck6L4KuZtLshxu0F6gID6z8dw27Ea0mT7Ea/KVezngwn2hE7W55T7vV3sTQn831XLnLIOhG/m7F3LJtGMHBEQ9Z8Stiyfx8D+8xOK5Snf4iAHrAGmjTIruc6+dHh5Gft8icHZOiORc+QN4No9RduI/MKiZVoArS27bXbtcRU5Gbq41p2GVnw7AfhO09Ewl+6BZBydnc+uLaHcqrzXa/vHrEDWKsJlQehhFsNjG0eWbgm0d58T+iVOrBPcF7Saz/D6Oe3hhQD2za/UdRM/R8wHm7L6AIIE4GK9do5cWyVjg25l+gNzHgoylx6yrA2wGrsgb00bp5HZ4sQxqYT6L1xR5mTfZlVi/UdtU5mPKL6Giq4LRK4wx6xro4UtL3vGbtbQ/0XtCvKfP1Unk5UgDqkDztWguEALKYrzz2jItHYxMjJ8j5euV4BroDLp1UMSejoJ9MNem+KDc5yMN2XYq9MgnBtGIzLV3AZ/0YymI4k3l3huBopjMR5Zd8GrzCW7zdvLQRqIkUeYSnzFnN8izGeRS0oB56m8b0+aJOVwlEYWp8vSxTDEZHgWBQ9Jt/kBDWQDadAsMD7I+XOiF1Taz+up/8QRV36wppsexK4aPZJSFjGweG5ZS1J9NM=
    skip_existing: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
  - provider: script
    script: "./deploy_anaconda.sh"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "3.7"
