{% set name = "osm2gpd" %}
{% set version = environ.get("TRAVIS_TAG", "") %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/PhiladelphiaController/osm2gpd.git
  git_rev: {{ version }}

build:
  script_env: 
    - TRAVIS_TAG
  number: 0
  script : python setup.py install

requirements:
  host:
    - python
    - requests
    - geopandas

  run:
    - python
    - requests
    - geopandas

test:
  imports:
    - osm2gpd

about:
  home: https://github.com/PhiladelphiaController/osm2gpd
  license: MIT
  license_family: MIT
  summary: Scrape features from OpenStreetMaps' API and return a geopandas GeoDataFrame

extra:
  recipe-maintainers:
    - PhiladelphiaController
